/*
제약 조건 추가
ALTER TABLE 테이블명
ADD CONSTRAINT 테이블명_컬럼명_제약조건단축 제약조건유형(컬럼명);
EX) 제약조건 NOT NULL(X), UNIQUE(O)
*/
/*
제약 조건 추가, 삭제, 수정 연습
1. ADDRESS TABLE - HOST COLUMN - UNIQUE 추가
2. DATA DICT(user_constraints) 확인
3. HOST COLUMN 제약 조건 삭제
4. ADDRESS TABLE - HOST COLUMN - NOT NULL 변경
5. DATA DICT(user_constraints) 확인
*/
-- 1. 
ALTER TABLE ADDRESS
ADD CONSTRAINT ADDRESS_HOST_UQ UNIQUE(HOST);

-- 2.
SELECT * FROM USER_CONSTRAINTS
WHERE TABLE_NAME='ADDRESS';

-- 3.
ALTER TABLE ADDRESS
DROP CONSTRAINT ADDRESS_HOST_UQ;

-- 4. 
-- (제약조건 유형에 따라 ADD와 MODIFY를 구분해서 쓴다)
-- NOT NULL -> ADD(X), MODIFY(O)
ALTER TABLE ADDRESS
MODIFY HOST CONSTRAINT ADDRESS_HOST_NN NOT NULL;

-- 5.
SELECT * FROM USER_CONSTRAINTS
WHERE TABLE_NAME='ADDRESS';

/*
확인예제
1. EMP TABLE -> COPY EMP07
2. ENAME - UNIQUE
3. DELETE ENAME UNIQUE
4. ENAME - NOT NULL
*/
-- 1.
CREATE TABLE EMP07
AS SELECT * FROM EMP;

-- 2.
ALTER TABLE EMP07
ADD CONSTRAINT EMP07_ENAME_UQ UNIQUE (ENAME);

-- 3.
ALTER TABLE EMP07
DROP CONSTRAINT EMP07_ENAME_UQ;

-- 4.
ALTER TABLE EMP07
MODIFY ENAME CONSTRAINT EMP07_ENAME_NN NOT NULL;

/*
제약조건 활성 및 비활성화 처리
ALTER TABLE 테이블명
ENABLE(DISABLE) CONSTRAINT 제약조건명;
*/
-- EX) EMP07 - EMP07_ENAME_NN DISABLE
ALTER TABLE EMP07
DISABLE CONSTRAINT EMP07_ENAME_NN;

-- 확인
SELECT * FROM USER_CONSTRAINTS
WHERE TABLE_NAME='EMP07';

-- ENABLE
ALTER TABLE EMP07
DISABLE CONSTRAINT EMP07_ENAME_NN;

