/*
SEQUENCE
PRIMARY KEY 자동 생성
SEQUENCE명.NEXTVAL
'CODE'||SEQUENCE명.NEXTVAL

CREATE SEQUENCE 시퀀스명
START WITH N - 시작번호
INCREMENT BY N - 증감단위
MAXVALUE N - 최대범위

시퀀스명.NEXTVAL - 현재값 증가 후 출력
시퀀스명.CURRVAL - 현재값 출력
*/
CREATE SEQUENCE EXP01_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999999;

SELECT EXP01_SEQ.NEXTVAL FROM DUAL;
SELECT EXP01_SEQ.CURRVAL FROM DUAL;

CREATE TABLE STUDENT_SEQ_EXP
(
	NO		NUMBER PRIMARY KEY,
	NAME	VARCHAR2(50)
);

CREATE SEQUENCE STUDENT_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 99999;

INSERT INTO STUDENT_SEQ_EXP VALUES (STUDENT_SEQ.NEXTVAL, '이름입력');
COMMIT;
SELECT * FROM STUDENT_SEQ_EXP;

/*
EMP_SEQ_EXP(EMPNO, ENAME) 테이블 생성
EMP_SEQ10 시퀀스 생성
1000 - +1

COLLAGE(STUDID, NAME) 테이블 생성
COLLAGE_SEQ 시퀀스 생성
C020001 - +1

INSERT COLLAGE DATA
*/
CREATE TABLE EMP_SEQ_EXP
AS SELECT EMPNO, ENAME FROM EMP;

CREATE SEQUENCE EMP_SEQ10
START WITH 1000
INCREMENT BY 1
MAXVALUE 99999;

CREATE TABLE COLLAGE
(
	STUDID		VARCHAR2(20) PRIMARY KEY,
	NAME		VARCHAR2(20)
);

CREATE SEQUENCE COLLAGE_SEQ
START WITH 20001
INCREMENT BY 1
MAXVALUE 999999;

INSERT INTO COLLAGE VALUES ('C0'||COLLAGE_SEQ.NEXTVAL, '이름입력');
SELECT * FROM COLLAGE;