/*
SEQUENCE
PRIMARY KEY 자동 생성
SEQUENCE명.NEXTVAL
'CODE'||SEQUENCE명.NEXTVAL

CREATE SEQUENCE 시퀀스명
START WITH N - 시작번호
INCREMENT BY N - 증감단위
MAXVALUE N - 최대범위

시퀀스명.NEXTVAL - 현재값 증가 후 출력
시퀀스명.CURRVAL - 현재값 출력
*/
CREATE SEQUENCE EXP01_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999999;

SELECT EXP01_SEQ.NEXTVAL FROM DUAL;
SELECT EXP01_SEQ.CURRVAL FROM DUAL;

CREATE TABLE STUDENT_SEQ_EXP
(
	NO		NUMBER PRIMARY KEY,
	NAME	VARCHAR2(50)
);

CREATE SEQUENCE STUDENT_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 99999;

INSERT INTO STUDENT_SEQ_EXP VALUES (STUDENT_SEQ.NEXTVAL, '이름입력');
COMMIT;
SELECT * FROM STUDENT_SEQ_EXP;

/*
EMP_SEQ_EXP(EMPNO, ENAME) 테이블 생성
EMP_SEQ10 시퀀스 생성
1000 - +1

COLLAGE(STUDID, NAME) 테이블 생성
COLLAGE_SEQ 시퀀스 생성
C020001 - +1

INSERT COLLAGE DATA
*/
CREATE TABLE EMP_SEQ_EXP
AS SELECT EMPNO, ENAME FROM EMP;

CREATE SEQUENCE EMP_SEQ10
START WITH 1000
INCREMENT BY 1
MAXVALUE 99999;

CREATE TABLE COLLAGE
(
	STUDID		VARCHAR2(20) PRIMARY KEY,
	NAME		VARCHAR2(20)
);

CREATE SEQUENCE COLLAGE_SEQ
START WITH 20001
INCREMENT BY 1
MAXVALUE 999999;

INSERT INTO COLLAGE VALUES ('C0'||COLLAGE_SEQ.NEXTVAL, '이름입력');
SELECT * FROM COLLAGE;

/*
SEQUENCE 되돌아가는 방법
현재값 변경은 불가능, 지우고 다시 생성한다
*/
SELECT * FROM USER_SEQUENCES;

CREATE SEQUENCE EXP_SEQ
START WITH 10
INCREMENT BY 10
MAXVALUE 70;

SELECT EXP_SEQ.NEXTVAL FROM DUAL;

DROP SEQUENCE EXP_SEQ;

SELECT * FROM USER_SEQUENCES
WHERE SEQUENCE_NAME='EXP_SEQ';

CREATE SEQUENCE EXP_SEQ
START WITH 50
INCREMENT BY 10
MAXVALUE 70;

SELECT * FROM USER_SEQUENCES
WHERE SEQUENCE_NAME='EXP_SEQ';

SELECT EXP_SEQ.NEXTVAL FROM DUAL;

/*
형식
ALTER SEQUENCE 시퀀스 이름
START WITH를 제외한 모든 옵션 설정가능
최대치 변경 - MAXVALUE
최대치 이후 다시 초기값 - CYCLE|NOCYCLE(DEFAULT)
CACHE - 빠른 처리를 위해 메모리 설정 1보다 크게 설정하며
		CYCLE 옵션이 설정될 때, 설정해주는 것이 일반적이다.
*/
ALTER SEQUENCE EXP_SEQ
	MINVALUE 10
	MAXVALUE 100
	CYCLE
	CACHE 5;

SELECT EXP_SEQ.NEXTVAL FROM DUAL;

/*
확인예제
1. 초기값 1000, 최대값 2000, 증가치 100인 시퀀스 생성
2. 실행 및 확인
3. DROP 시키고, 초기값 1100
4. 변경 - 최소값 1100, 증가치 10, 최대값 2000, CYCLE
*/
DROP SEQUENCE EXP_SEQ01;

CREATE SEQUENCE EXP_SEQ01
START WITH 1100
INCREMENT BY 100
MAXVALUE 2000;

SELECT EXP_SEQ01.NEXTVAL FROM DUAL;

ALTER SEQUENCE EXP_SEQ01
MINVALUE 1100
INCREMENT BY 10
CYCLE
CACHE 5;

