/*
ROLE
용도에 맞게 권한을 묶어놓은 것
1. CONNECT
DB 접속용 기본적인 권한
EX) ALTER SESSION, CREATE CLUSTER, CREATE DATABASE LINK,
CREATE SEQUENCE, CREATE SESSION, CREATE SYNONYM,
CREATE TABLE, CREATE VIEW
2. RESOURCE
객체(TABLE, VIEW, INDEX 등) 생성 권한
CREATE CLUSTER, CREATE PROCEDURE, CREATE EQUENCE,
CREATE TABLE, CREATE TRIGGER
3. DBA
ADMIN 용

활용순서
1. ROLE 생성(DBA가 생성)
	형식) CREATE ROLE 롤이름
2. ROLE에 권한부여
	형식) GRANT 권한1, 권한2, 권한3 TO 롤의 이름
3. ##사용자에 롤을 부여.
	형식) GRANT 롤이름 TO 사용자
*/
CREATE ROLE ROLEEXP01;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW
		TO ROLEEXP01;
GRANT ROLEEXP01 TO SCOTT01;
